name: loci
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - h5py=3.6
  - libpng=1.6
  - matplotlib=3.5
  - numpy=1.21
  - python=3.9
  - pytorch=1.10
  - torchaudio=0.10
  - torchvision=0.11
  - pip==22.2.2
  - pip:
    - einops
    - jsmin
    - opencv-python
    - pandas
    - pytorch-msssim
    - mnist
